### ISSUE TITLE
Problems with quick start 'setup' command

### ISSUE THREAD

**Issue by gxclarke** [h5p/h5p-cli#119]
Hello there!

I'm following the quick start guide in the README and would like to report some problems running the following command:

`h5p setup h5p-course-presentation`

The installation fails with the following:

```
Error: ENOTEMPTY: directory not empty, rmdir 'libraries/H5P.OpenEndedQuestion-1.0/node_modules'
```

The node_modules folder contains a hidden `.DS_Store` file. Reading about this, it seems auto-created on Macs. Did the author accidentally commit it? Fixed by:

`rm -rf node_modules`

And then re-running the h5p setup command.

Next, the same problem, but this time with:

```
Error: ENOTEMPTY: directory not empty, rmdir 'libraries/H5P.Dialogcards-1.9/node_modules'
```

After re-running again:

```
>> ~ updating to h5p-editor-vertical-tabs 1.3.9
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
> error
Error: Command failed: git pull origin
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
```

I am still looking for a workaround for this one.

**Comment by gxclarke** [comment]
I tried again today, and I did not encounter the directory not being empty problems. Presumably, this is a local issue on my machine, so let's disregard it.

Regarding the unstaged changes, the following screenshot shows the unstaged change:

![image](https://github.com/user-attachments/assets/1b40f9bb-59ad-42b3-b57c-6bcdd30b2f5d)

**Comment by otacke** [comment]
@gxclarke I think all you need to do is what git tells you to: Stash those unstaged commits of your's, done.

**Comment by gxclarke** [comment]
@otacke I haven't made any changes. This is resulting from `h5p setup h5p-course-presentation` (from the quick start guide in the readme). Yes, I can stash the change, but the setup errored out at this point.

**Comment by gxclarke** [comment]
Apologies for not making this clearer, but the rebase error causes H5P to error out:

![image](https://github.com/user-attachments/assets/d419be6e-b5b9-4298-8f98-6b6006aa83c0)

**Comment by otacke** [comment]
@gxclarke I don't think that I can reproduce this. Maybe tomorrow will shed some more light on things.

**Comment by otacke** [comment]
@gxclarke Sorry, can't reproduce this on my end. `h5p setup h5p-course-presentation` does its job just file here, even if run multiple times with the `h5p-editor-vertical-tabs` library having been build in the first run.

@devland is the main developer of the H5P CLI tool (I am not a member of the H5P core team). Maybe he can reproduce the issue.

**Comment by devland** [comment]
I could not reproduce any of the above.
If you have unstaged commits in any of the libraries that the h5p-cli tries to update then the process will fail with the "You have unstaged changes." error. In this case, if you cannot commit your changes, then you can either run the setup command with the `H5P_NO_UPDATES=1` flag (`H5P_NO_UPDATES=1 h5p setup h5p-course-presentation`) or run the regular command in a new work dir that has no other libraries set up.
