### ISSUE TITLE
Editing interface should be totally translated

### ISSUE THREAD

**Issue by rezeau** [h5p/h5p-cli#123]
In the h5p-cli server interface dashboard a Language option is available. Unfortunately, when editing an h5p content, the editing interface is only minimally translated and a lot of the language displayed remain in English rather than the selection Language option. The attached screenshot illustrates the issue. Where I have marked with a tick the translated items and with a cross those which are NOT translated.
This is a _serious issue_ when creating or checking languages for the editing interface of an h5p content. And a fix should really be considered.
Similar issue in the development mode of Drupal.
No such problem in Lumi, which correctly displays the editing interface in the selected language!
![2024-11-21_16-24-02](https://github.com/user-attachments/assets/3290088b-0189-47d3-ad1b-92431f2cb0e7)

**Comment by otacke** [comment]
@devland Where else would the issue be?

**Comment by otacke** [comment]
Created https://h5ptechnology.atlassian.net/browse/HFP-4170.

**Comment by rezeau** [comment]
@devland Please re-open this issue which should not have been closed... and provide a fix.
