### ISSUE TITLE
Loading semantics, please wait...

### ISSUE THREAD

**Issue by woldtwerk** [h5p/h5p-cli#24]
Fill the blanks is running just fine. I can modify settings and content in the .json and js files.
I can't get the editor working though. All I get is "Loading semantics, please wait..."
Am I missing something?

**Comment by icc** [comment]
Try opening your browser console(Ctrl+Shift+J in Chrome/Firefox) and look for any errors.

**Comment by Wursthandschuh** [comment]
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (h5peditor.js:72)
    at c (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at k (jquery.js:4)
    at XMLHttpRequest.r (jquery.js:4)

I got some undefined strings there. Those can't be parsed. E.g. libraryData.language

**Comment by icc** [comment]
There appears to be an error in one of the translation files. What language are you using?

**Comment by Wursthandschuh** [comment]
Well, the interface is in english. I didn't set it to english anywhere though. I did not see or got asked to set any language.

**Comment by JulianSSS** [comment]
Hi,
since (in that case Blanks) has a minor version 12 which has two digits. That leads to h5peditor.js not handling the libraryFromString correctly, because the regExp is demanding a single digit as minor version.

**Comment by JulianSSS** [comment]
Hi Frode,
@icc as vou can see, I made a PR for handling multi-digit-versioned Libraries correctly.

**Comment by Wursthandschuh** [comment]
The fix by @JulianSSS works for me.

**Comment by devland** [comment]
h5p-cli core functionality has been rewritten. Closing this since it is no longer relevant.
