### ISSUE TITLE
Add missing dependencies to H5P registry

### ISSUE THREAD

**Issue by ghost** [h5p/h5p-cli#28]
Hey,

Trying to develop / improve existing  H5P modules using this CLI tool, but it is missing `h5p-editor-show-when` in the list of modules.

Getting messages inside drupal like:

"Missing dependency XXX required by YYY to registry" 

Following the code here, I am guessing the API for the CLI tool, `https://h5p.org/registry.json` is not yet updated with the latest available H5P modules yet.

I followed these instructions: https://h5p.org/development-environment to setup with drupal 7 and the H5P cli tool. Installing the true false module with get `h5p get h5p-true-false` inside h5p's development folder. True false shows up in the hub as installed, but gives the missing dependency error.

As a fallback I tried to use plain git clone on the missing H5P module repo (h5p-editor-show-when) inside the development folder, but this did not help.

Upon adding h5p true false content I receive this error in the console, thrown by h5peditor:

```
VM2395 h5peditor.js:422 Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.ns.processSemanticsChunk (VM2395 h5peditor.js:422)
    at new MetadataForm (VM2429 h5peditor-metadata.js:293)
    at ns.Form.processSemantics (VM2407 h5peditor-form.js:422)
    at VM2405 h5peditor-library-selector.js:269
    at VM2395 h5peditor.js:224
    at VM2395 h5peditor.js:142
    at HTMLScriptElement.script.onload (VM2395 h5peditor.js:78)
```

Let me know if any more info is required to debug.

**Missing dependencies so far**:

- [ ] h5p-editor-show-when required for: h5p-true-false, multiChoice, ...
- [ ] h5p-editor-rangelist required for at least: h5p-summary, ...

**Comment by rvantonisse-accessibility** [comment]
I tried to add the multi choice module as well, same error.

**Comment by rvantonisse-accessibility** [comment]
H5PEditor.RangeList also seems to be missing from the registry

**Comment by hdagheda** [comment]
Is there any updates on this issue? I'm having same issue while adding course presentation
```
Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.ns.processSemanticsChunk (h5peditor.js?ver=2020082800:422)
    at new MetadataForm (h5peditor-metadata.js?ver=2020082800:293)
    at ns.Form.processSemantics (h5peditor-form.js?ver=2020082800:422)
    at h5peditor-library-selector.js?ver=2020082800:269
    at h5peditor.js?ver=2020082800:224
    at h5peditor.js?ver=2020082800:142
    at HTMLScriptElement.script.onload (h5peditor.js?ver=2020082800:78)``
```

**Comment by rvantonisse** [comment]
Hey 👋 ,

ℹ️ For your information:
checking in here as the "Ghost 👻 " commenter. I have merged my work related account, rvantonisse-accessibility, with my personal one.

And now that I am here: is this issue still relevant for the h5p-cli? Any updates or comment?

Cheers,
Roel

**Comment by devland** [comment]
h5p-cli core functionality has been rewritten. Closing this since it is no longer relevant.
