### ISSUE TITLE
Potentially forward from `http://localhost:8080` to `http://localhost:8080/dashboard`

### ISSUE THREAD

**Issue by otacke** [h5p/h5p-cli#56]
It feels a little unintuitive to be required to point your browser towards a specific endpoint if you just wanted to launch the environment. Unless `http://localhost:8080` is reserved for something else in the future, it might be worth forwarding to `http://localhost:8080/dashboard` by default or just add another route to the express configuration.

https://github.com/h5p/h5p-cli/blob/d7391db10bb67dffb2a9e20e460de681ab17d285/readme.md?plain=1#L28-L29
https://github.com/h5p/h5p-cli/blob/d7391db10bb67dffb2a9e20e460de681ab17d285/commands.md?plain=1#L76-L77

**Comment by devland** [comment]
Done.
https://github.com/h5p/h5p-cli/pull/60
