### ISSUE TITLE
missing library issue

### ISSUE THREAD

**Issue by hosais** [h5p/h5p-cli#6]
Hi,
I run a h5p server with main content "h5p-course-presentation". I can see my content from the server I run without problems. But I got following message on the server console:
Missing library: Drop
Missing library: H5P.TwitterUserFeed

There are different ways to have lib list. 
The way I have h5p-libs:
-- "h5p get h5p-course-presentation" to clone all related h5p libs.
Code path: h5p-cli.js -> h5p.get = function (libraries, next) { ..}
-> get lib list from "https://h5p.org/registry.json"
Run server:
-- h5p server
Code path: h5p-server.js -> h5p-library-list.js,  H5PLibraryList.fromDirectory
-> get lib list starting from main content

Which would be the right way?

**Comment by hosais** [comment]
Hi again,  
I just downloaded h5p-twitter-user-feed and h5p/drop from repo and the messages disappear.

**Comment by fnoks** [comment]
Hi,

Good to hear you found a solution to this. The reason for this is the library registry on h5p.org (used by the h5p cli) is not completely up to date, i.e. it is missing a few libraries. We will fix this asap, so that others don't experience the same as you!

Thanks for reporting!

**Comment by hosais** [comment]
Thanks for your info, fnoks.

**Comment by fnoks** [comment]
FYI: The library registry on h5p.org is now updated.
